### ISSUE TITLE
Dimensions must be equal, but are 0 and 3

### ISSUE THREAD

**Issue by ManoaNosea** [kostyaev/ICNR#2]
```
def conv2(batch_input, kernel=3, output_channel=64, stride=1, use_bias=True, scope='conv'):
    # kernel: An integer specifying the width and height of the 2D convolution window
    with tf.variable_scope(scope):     
        if use_bias:
            return slim.conv2d(batch_input, output_channel, [kernel, kernel], stride, 'SAME', data_format='NHWC',
                            activation_fn=None, weights_initializer=tf.contrib.layers.xavier_initializer())
        else:
            return slim.conv2d(batch_input, output_channel, [kernel, kernel], stride, 'SAME', data_format='NHWC',
                            activation_fn=None, weights_initializer=tf.contrib.layers.xavier_initializer(),
                            biases_initializer=None)
```

```
def conv2(batch_input, kernel=3, output_channel=64, stride=1, use_bias=True, scope='conv'):
    # kernel: An integer specifying the width and height of the 2D convolution window
    with tf.variable_scope(scope):     
        if use_bias:
            return slim.conv2d(batch_input, output_channel, [kernel, kernel], stride, 'SAME', data_format='NHWC',
                            activation_fn=None, weights_initializer=ICNR(tf.glorot_uniform_initializer(), scale=2))
        else:
            return slim.conv2d(batch_input, output_channel, [kernel, kernel], stride, 'SAME', data_format='NHWC',
                            activation_fn=None, weights_initializer=ICNR(tf.glorot_uniform_initializer(), scale=2),
                            biases_initializer=None)
```

```
Traceback (most recent call last):
  File "E:\programs\WPy64-3680\python-3.6.8.amd64\lib\site-packages\tensorflow\python\framework\ops.py", line 1576, in _create_c_op
    c_op = c_api.TF_FinishOperation(op_desc)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Dimensions must be equal, but are 0 and 3 for 'generator/generator_unit/output_stage/conv/Conv/BiasAdd' (op: 'BiasAdd') with input shapes: [36,96,96,0], [3].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 297, in <module>
    Net = SRResnet(data.inputs, data.targets, FLAGS)
  File "Y:\theshitt-backup\Projects\AINeuralNetSuperRes\retired systems\brade4\lib\model.py", line 518, in SRResnet
    gen_output = generator(inputs, output_channel, reuse=False, FLAGS=FLAGS)
  File "Y:\theshitt-backup\Projects\AINeuralNetSuperRes\retired systems\brade4\lib\model.py", line 291, in generator
    net = conv2(net, 9, gen_output_channels, 1, scope='conv')
  File "Y:\theshitt-backup\Projects\AINeuralNetSuperRes\retired systems\brade4\lib\ops.py", line 50, in conv2
    activation_fn=None, weights_initializer=ICNR(tf.glorot_uniform_initializer(), scale=2))
  File "E:\programs\WPy64-3680\python-3.6.8.amd64\lib\site-packages\tensorflow\contrib\framework\python\ops\arg_scope.py", line 183, in func_with_args
    return func(*args, **current_args)
  File "E:\programs\WPy64-3680\python-3.6.8.amd64\lib\site-packages\tensorflow\contrib\layers\python\layers\layers.py", line 1154, in convolution2d
    conv_dims=2)
  File "E:\programs\WPy64-3680\python-3.6.8.amd64\lib\site-packages\tensorflow\contrib\framework\python\ops\arg_scope.py", line 183, in func_with_args
    return func(*args, **current_args)
  File "E:\programs\WPy64-3680\python-3.6.8.amd64\lib\site-packages\tensorflow\contrib\layers\python\layers\layers.py", line 1057, in convolution
    outputs = layer.apply(inputs)
  File "E:\programs\WPy64-3680\python-3.6.8.amd64\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 805, in apply
    return self.__call__(inputs, *args, **kwargs)
  File "E:\programs\WPy64-3680\python-3.6.8.amd64\lib\site-packages\tensorflow\python\layers\base.py", line 362, in __call__
    outputs = super(Layer, self).__call__(inputs, *args, **kwargs)
  File "E:\programs\WPy64-3680\python-3.6.8.amd64\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 736, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "E:\programs\WPy64-3680\python-3.6.8.amd64\lib\site-packages\tensorflow\python\keras\layers\convolutional.py", line 210, in call
    outputs = nn.bias_add(outputs, self.bias, data_format='NHWC')
  File "E:\programs\WPy64-3680\python-3.6.8.amd64\lib\site-packages\tensorflow\python\ops\nn_ops.py", line 1506, in bias_add
    return gen_nn_ops.bias_add(value, bias, data_format=data_format, name=name)
  File "E:\programs\WPy64-3680\python-3.6.8.amd64\lib\site-packages\tensorflow\python\ops\gen_nn_ops.py", line 729, in bias_add
    "BiasAdd", value=value, bias=bias, data_format=data_format, name=name)
  File "E:\programs\WPy64-3680\python-3.6.8.amd64\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "E:\programs\WPy64-3680\python-3.6.8.amd64\lib\site-packages\tensorflow\python\util\deprecation.py", line 454, in new_func
    return func(*args, **kwargs)
  File "E:\programs\WPy64-3680\python-3.6.8.amd64\lib\site-packages\tensorflow\python\framework\ops.py", line 3155, in create_op
    op_def=op_def)
  File "E:\programs\WPy64-3680\python-3.6.8.amd64\lib\site-packages\tensorflow\python\framework\ops.py", line 1731, in __init__
    control_input_ops)
  File "E:\programs\WPy64-3680\python-3.6.8.amd64\lib\site-packages\tensorflow\python\framework\ops.py", line 1579, in _create_c_op
    raise ValueError(str(e))
ValueError: Dimensions must be equal, but are 0 and 3 for 'generator/generator_unit/output_stage/conv/Conv/BiasAdd' (op: 'BiasAdd') with input shapes: [36,96,96,0], [3].
```

need a littel help, any ideas what can be the problem ? thank you :)

**Comment by ManoaNosea** [comment]
I disabled bias but now I have another error of same type:
```
Traceback (most recent call last):
  File "E:\programs\WPy64-3680\python-3.6.8.amd64\lib\site-packages\tensorflow\python\framework\ops.py", line 525, in set_shape
    unknown_shape)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Dimension 3 in both shapes must be equal, but are 0 and 3. Shapes are [36,96,96,0] and [36,96,96,3].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 297, in <module>
    Net = SRResnet(data.inputs, data.targets, FLAGS)
  File "Y:\theshitt-backup\Projects\AINeuralNetSuperRes\retired systems\brade4\lib\model.py", line 519, in SRResnet
    gen_output.set_shape([FLAGS.batch_size, FLAGS.crop_size * 4, FLAGS.crop_size * 4, 3])
  File "E:\programs\WPy64-3680\python-3.6.8.amd64\lib\site-packages\tensorflow\python\framework\ops.py", line 528, in set_shape
    raise ValueError(str(e))
```

**Comment by ManoaNosea** [comment]
I wrote this insted but it gived same error:
```
    with tf.variable_scope(scope):     
        if use_bias:
            return slim.conv2d(batch_input, output_channel, [kernel, kernel], stride, 'SAME', data_format='NHWC',
                            activation_fn=None, weights_initializer=ICNR(tf.contrib.layers.xavier_initializer(), scale=2))
        else:
            return slim.conv2d(batch_input, output_channel, [kernel, kernel], stride, 'SAME', data_format='NHWC',
                            activation_fn=None, weights_initializer=ICNR(tf.contrib.layers.xavier_initializer(), scale=2),
                            biases_initializer=None)
```

**Comment by ManoaNosea** [comment]
a funny thing heppens when I change scale to 3:
```
Traceback (most recent call last):
  File "E:\programs\WPy64-3680\python-3.6.8.amd64\lib\site-packages\tensorflow\python\framework\ops.py", line 1576, in _create_c_op
    c_op = c_api.TF_FinishOperation(op_desc)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Dimensions must be equal, but are 63 and 64 for 'generator/generator_unit/input_stage/conv/Conv/BiasAdd' (op: 'BiasAdd') with input shapes: [1,?,?,63], [64].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 226, in <module>
    gen_output = generator(inputs_raw, 3, reuse=False, FLAGS=FLAGS)
  File "Y:\theshitt-backup\Projects\AINeuralNetSuperRes\retired systems\brade4\lib\model.py", line 256, in generator
    net = conv2(gen_inputs, 9, 64, 1, scope='conv')
  File "Y:\theshitt-backup\Projects\AINeuralNetSuperRes\retired systems\brade4\lib\ops.py", line 50, in conv2
    activation_fn=None, weights_initializer=ICNR(tf.contrib.layers.xavier_initializer(), scale=3))
  File "E:\programs\WPy64-3680\python-3.6.8.amd64\lib\site-packages\tensorflow\contrib\framework\python\ops\arg_scope.py", line 183, in func_with_args
    return func(*args, **current_args)
  File "E:\programs\WPy64-3680\python-3.6.8.amd64\lib\site-packages\tensorflow\contrib\layers\python\layers\layers.py", line 1154, in convolution2d
    conv_dims=2)
  File "E:\programs\WPy64-3680\python-3.6.8.amd64\lib\site-packages\tensorflow\contrib\framework\python\ops\arg_scope.py", line 183, in func_with_args
    return func(*args, **current_args)
  File "E:\programs\WPy64-3680\python-3.6.8.amd64\lib\site-packages\tensorflow\contrib\layers\python\layers\layers.py", line 1057, in convolution
    outputs = layer.apply(inputs)
  File "E:\programs\WPy64-3680\python-3.6.8.amd64\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 805, in apply
    return self.__call__(inputs, *args, **kwargs)
  File "E:\programs\WPy64-3680\python-3.6.8.amd64\lib\site-packages\tensorflow\python\layers\base.py", line 362, in __call__
    outputs = super(Layer, self).__call__(inputs, *args, **kwargs)
  File "E:\programs\WPy64-3680\python-3.6.8.amd64\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 736, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "E:\programs\WPy64-3680\python-3.6.8.amd64\lib\site-packages\tensorflow\python\keras\layers\convolutional.py", line 210, in call
    outputs = nn.bias_add(outputs, self.bias, data_format='NHWC')
  File "E:\programs\WPy64-3680\python-3.6.8.amd64\lib\site-packages\tensorflow\python\ops\nn_ops.py", line 1506, in bias_add
    return gen_nn_ops.bias_add(value, bias, data_format=data_format, name=name)
  File "E:\programs\WPy64-3680\python-3.6.8.amd64\lib\site-packages\tensorflow\python\ops\gen_nn_ops.py", line 729, in bias_add
    "BiasAdd", value=value, bias=bias, data_format=data_format, name=name)
  File "E:\programs\WPy64-3680\python-3.6.8.amd64\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "E:\programs\WPy64-3680\python-3.6.8.amd64\lib\site-packages\tensorflow\python\util\deprecation.py", line 454, in new_func
    return func(*args, **kwargs)
  File "E:\programs\WPy64-3680\python-3.6.8.amd64\lib\site-packages\tensorflow\python\framework\ops.py", line 3155, in create_op
    op_def=op_def)
  File "E:\programs\WPy64-3680\python-3.6.8.amd64\lib\site-packages\tensorflow\python\framework\ops.py", line 1731, in __init__
    control_input_ops)
  File "E:\programs\WPy64-3680\python-3.6.8.amd64\lib\site-packages\tensorflow\python\framework\ops.py", line 1579, in _create_c_op
    raise ValueError(str(e))
ValueError: Dimensions must be equal, but are 63 and 64 for 'generator/generator_unit/input_stage/conv/Conv/BiasAdd' (op: 'BiasAdd') with input shapes: [1,?,?,63], [64].
```
